/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BitRouteImport } from './routes/bit'
import { Route as CombinedRouteImport } from './routes/combined'
import { Route as ConquestRouteImport } from './routes/conquest'
import { Route as EngageRouteImport } from './routes/engage'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as PlayRouteImport } from './routes/play'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as RatingsIndexRouteImport } from './routes/ratings/index'
import { Route as RatingsFideIdRouteImport } from './routes/ratings/$fideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BitRoute = BitRouteImport.update({
  id: '/bit',
  path: '/bit',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinedRoute = CombinedRouteImport.update({
  id: '/combined',
  path: '/combined',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquestRoute = ConquestRouteImport.update({
  id: '/conquest',
  path: '/conquest',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageRoute = EngageRouteImport.update({
  id: '/engage',
  path: '/engage',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsIndexRoute = RatingsIndexRouteImport.update({
  id: '/ratings/',
  path: '/ratings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsFideIdRoute = RatingsFideIdRouteImport.update({
  id: '/ratings/$fideId',
  path: '/ratings/$fideId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/bit': typeof BitRoute
  '/combined': typeof CombinedRoute
  '/conquest': typeof ConquestRoute
  '/engage': typeof EngageRoute
  '/events': typeof EventsRoute
  '/learn': typeof LearnRoute
  '/ops': typeof OpsRoute
  '/platforms': typeof PlatformsRoute
  '/play': typeof PlayRoute
  '/tournaments': typeof TournamentsRoute
  '/ratings/$fideId': typeof RatingsFideIdRoute
  '/ratings/': typeof RatingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/bit': typeof BitRoute
  '/combined': typeof CombinedRoute
  '/conquest': typeof ConquestRoute
  '/engage': typeof EngageRoute
  '/events': typeof EventsRoute
  '/learn': typeof LearnRoute
  '/ops': typeof OpsRoute
  '/platforms': typeof PlatformsRoute
  '/play': typeof PlayRoute
  '/tournaments': typeof TournamentsRoute
  '/ratings/$fideId': typeof RatingsFideIdRoute
  '/ratings': typeof RatingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/bit': typeof BitRoute
  '/combined': typeof CombinedRoute
  '/conquest': typeof ConquestRoute
  '/engage': typeof EngageRoute
  '/events': typeof EventsRoute
  '/learn': typeof LearnRoute
  '/ops': typeof OpsRoute
  '/platforms': typeof PlatformsRoute
  '/play': typeof PlayRoute
  '/tournaments': typeof TournamentsRoute
  '/ratings/$fideId': typeof RatingsFideIdRoute
  '/ratings/': typeof RatingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/agents'
    | '/bit'
    | '/combined'
    | '/conquest'
    | '/engage'
    | '/events'
    | '/learn'
    | '/ops'
    | '/platforms'
    | '/play'
    | '/tournaments'
    | '/ratings/$fideId'
    | '/ratings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/agents'
    | '/bit'
    | '/combined'
    | '/conquest'
    | '/engage'
    | '/events'
    | '/learn'
    | '/ops'
    | '/platforms'
    | '/play'
    | '/tournaments'
    | '/ratings/$fideId'
    | '/ratings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/agents'
    | '/bit'
    | '/combined'
    | '/conquest'
    | '/engage'
    | '/events'
    | '/learn'
    | '/ops'
    | '/platforms'
    | '/play'
    | '/tournaments'
    | '/ratings/$fideId'
    | '/ratings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  BitRoute: typeof BitRoute
  CombinedRoute: typeof CombinedRoute
  ConquestRoute: typeof ConquestRoute
  EngageRoute: typeof EngageRoute
  EventsRoute: typeof EventsRoute
  LearnRoute: typeof LearnRoute
  OpsRoute: typeof OpsRoute
  PlatformsRoute: typeof PlatformsRoute
  PlayRoute: typeof PlayRoute
  TournamentsRoute: typeof TournamentsRoute
  RatingsFideIdRoute: typeof RatingsFideIdRoute
  RatingsIndexRoute: typeof RatingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bit': {
      id: '/bit'
      path: '/bit'
      fullPath: '/bit'
      preLoaderRoute: typeof BitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combined': {
      id: '/combined'
      path: '/combined'
      fullPath: '/combined'
      preLoaderRoute: typeof CombinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquest': {
      id: '/conquest'
      path: '/conquest'
      fullPath: '/conquest'
      preLoaderRoute: typeof ConquestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage': {
      id: '/engage'
      path: '/engage'
      fullPath: '/engage'
      preLoaderRoute: typeof EngageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings/': {
      id: '/ratings/'
      path: '/ratings'
      fullPath: '/ratings/'
      preLoaderRoute: typeof RatingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings/$fideId': {
      id: '/ratings/$fideId'
      path: '/ratings/$fideId'
      fullPath: '/ratings/$fideId'
      preLoaderRoute: typeof RatingsFideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  BitRoute: BitRoute,
  CombinedRoute: CombinedRoute,
  ConquestRoute: ConquestRoute,
  EngageRoute: EngageRoute,
  EventsRoute: EventsRoute,
  LearnRoute: LearnRoute,
  OpsRoute: OpsRoute,
  PlatformsRoute: PlatformsRoute,
  PlayRoute: PlayRoute,
  TournamentsRoute: TournamentsRoute,
  RatingsFideIdRoute: RatingsFideIdRoute,
  RatingsIndexRoute: RatingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
